services:

  trainer:
    build:
      context: .
      dockerfile: Dockerfile.trainer
    container_name: minigrid_trainer
    command: python src/train_all.py
    volumes:
      - ./data:/app/data
      - ./checkpoints:/app/checkpoints
      - ./runs:/app/runs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    develop:
      watch:
        - path: ./src
          action: sync
          target: /app/src
        - path: ./requirements.trainer.txt
          action: rebuild

  tensorboard:
    build:
      context: .
      dockerfile: Dockerfile.trainer
    container_name: minigrid_tensorboard
    command: tensorboard --logdir /app/runs --host 0.0.0.0 --port 6006 --load_fast=false
    ports:
      - "6006:6006"    # Dashboard métriques : http://localhost:6006
    volumes:
      - ./runs:/app/runs
